apiVersion: v1
kind: Service
metadata:
  name: llava-model
  namespace: baudelair
spec:
  selector:
    app: llava-model
  ports:
  - protocol: TCP
    port: 11434
    targetPort: 11434
  type: ClusterIP